=== ermiS16/DeklrarativeProgrammierung/src/aufgabe2/rechnung.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT RECHNUNGEN (RECHNUNG+)>
<!ELEMENT RECHNUNG (UNTERNEHMEN, ADRESSAT, RECHNUNGSDETAILS, PRODUKTE)>

<!ELEMENT UNTERNEHMEN (NAME, ADRESSE, TELEFON, FAX, EMAIL, STEUERNUMMER)>
<!ELEMENT NAME (#PCDATA)>

<!ELEMENT ADRESSE (STRASSE, HAUSNUMMER, PLZ, ORT)>
<!ELEMENT STRASSE (#PCDATA)>
<!ELEMENT HAUSNUMMER (#PCDATA)>
<!ELEMENT PLZ (#PCDATA)>
<!ELEMENT ORT (#PCDATA)>

<!ELEMENT TELEFON (#PCDATA)>
<!ELEMENT FAX (#PCDATA)>
<!ELEMENT EMAIL (#PCDATA)>
<!ELEMENT STEUERNUMMER (#PCDATA)>

<!ELEMENT ADRESSAT (ANREDE, NAME, ADRESSE)>
<!ELEMENT ANREDE (#PCDATA)>

<!ELEMENT RECHNUNGSDETAILS (RECHNUNGSDATUM, RECHNUNGSNUMMER, BETRAG)>
<!ELEMENT RECHNUNGSDATUM (#PCDATA)>
<!ELEMENT RECHNUNGSNUMMER (#PCDATA)>
<!ELEMENT BETRAG (BRUTTO_GESAMT, NETTO_GESAMT, MWST_GESAMT)>
<!ELEMENT BRUTTO_GESAMT (#PCDATA)>
<!ELEMENT NETTO_GESAMT (#PCDATA)>
<!ELEMENT MWST_GESAMT (#PCDATA)>

<!ELEMENT PRODUKTE (PRODUKT)+>
<!ELEMENT PRODUKT (POSITION, ART, EINZELPREIS, GESAMTPREIS, MWST_PROZENT, DATUM)>
<!ELEMENT POSITION (#PCDATA)>
<!ELEMENT ART (#PCDATA)>
<!ATTLIST PRODUKT menge CDATA #REQUIRED>
<!ELEMENT EINZELPREIS (#PCDATA)>
<!ELEMENT GESAMTPREIS (#PCDATA)>
<!ELEMENT MWST_PROZENT (#PCDATA)>
<!ELEMENT DATUM (#PCDATA)>

=== ermiS16/DeklrarativeProgrammierung/src/aufgabe2/rechnung.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE RECHNUNG SYSTEM "rechnung.dtd">

<RECHNUNGEN>
	<RECHNUNG>
		<UNTERNEHMEN>
			<NAME>Kleintier Meier GmbH</NAME>
			<ADRESSE>
				<STRASSE>Meierring</STRASSE>
				<HAUSNUMMER>3</HAUSNUMMER>
				<PLZ>82828</PLZ>
				<ORT>Machthausen</ORT>
			</ADRESSE>
			<TELEFON>0777/987987</TELEFON>
			<FAX>0777/987789</FAX>
			<EMAIL>klein.meier@tiere.de</EMAIL>
			<STEUERNUMMER>88 123/8282 2</STEUERNUMMER>
		</UNTERNEHMEN>

		<ADRESSAT>
			<ANREDE>Frau</ANREDE>
			<NAME>Sybille</NAME>
			<ADRESSE>
				<STRASSE>Am Süttelbach</STRASSE>
				<HAUSNUMMER>17</HAUSNUMMER>
				<PLZ>77070</PLZ>
				<ORT>Siedelsuderstadt</ORT>
			</ADRESSE>
		</ADRESSAT>

		<RECHNUNGSDETAILS>
			<RECHNUNGSDATUM>15.1.2017</RECHNUNGSDATUM>
			<RECHNUNGSNUMMER>657321</RECHNUNGSNUMMER>
			<BETRAG>
				<BRUTTO_GESAMT>962.22</BRUTTO_GESAMT>
				<NETTO_GESAMT>808.59</NETTO_GESAMT>
				<MWST_GESAMT>153.63</MWST_GESAMT>
			</BETRAG>
		</RECHNUNGSDETAILS>

		<PRODUKTE>
			<PRODUKT menge="100">
				<POSITION>1</POSITION>
				<ART>Antike Holzwürmer</ART>
				<EINZELPREIS>1.50</EINZELPREIS>
				<GESAMTPREIS>150.00</GESAMTPREIS>
				<MWST_PROZENT>19</MWST_PROZENT>
				<DATUM>1.1.2017</DATUM>
			</PRODUKT>

			<PRODUKT menge="1">
				<POSITION>2</POSITION>
				<ART>Holzwurmfutter</ART>
				<EINZELPREIS>34.45</EINZELPREIS>
				<GESAMTPREIS>34.45</GESAMTPREIS>
				<MWST_PROZENT>19</MWST_PROZENT>
				<DATUM>12.1.2017</DATUM>
			</PRODUKT>

			<PRODUKT menge="1">
				<POSITION>3</POSITION>
				<ART>Steinlaus, Petrophaga lorioti</ART>
				<EINZELPREIS>777.77</EINZELPREIS>
				<GESAMTPREIS>777.77</GESAMTPREIS>
				<MWST_PROZENT>19</MWST_PROZENT>
				<DATUM>12.1.2017</DATUM>
			</PRODUKT>
		</PRODUKTE>
	</RECHNUNG>

	<RECHNUNG>
		<UNTERNEHMEN>
			<NAME>Rochade-La Hoff Pharma GmbH</NAME>
			<ADRESSE>
				<STRASSE>An der Chemie</STRASSE>
				<HAUSNUMMER>17</HAUSNUMMER>
				<PLZ>79639</PLZ>
				<ORT>Grenzych-Wahlen</ORT>
			</ADRESSE>
			<TELEFON>07624 / 666 333 999</TELEFON>
			<FAX>07624 / 666 333 990</FAX>
			<EMAIL>unter@berg.de</EMAIL>
			<STEUERNUMMER>DE333666999</STEUERNUMMER>
		</UNTERNEHMEN>

		<ADRESSAT>
			<ANREDE>Dr. med</ANREDE>
			<NAME>Cyprian Zottel</NAME>
			<ADRESSE>
				<STRASSE>Soddelstudel</STRASSE>
				<HAUSNUMMER>5a</HAUSNUMMER>
				<PLZ>13023</PLZ>
				<ORT>Zotenheim</ORT>
			</ADRESSE>
		</ADRESSAT>

		<RECHNUNGSDETAILS>
			<RECHNUNGSDATUM>8.8.2017</RECHNUNGSDATUM>
			<RECHNUNGSNUMMER>98-798-7987</RECHNUNGSNUMMER>
			<BETRAG>
				<BRUTTO_GESAMT>621.24</BRUTTO_GESAMT>
				<NETTO_GESAMT>490.22</NETTO_GESAMT>
				<MWST_GESAMT>116.74</MWST_GESAMT>
			</BETRAG>
		</RECHNUNGSDETAILS>

		<PRODUKTE>
			<PRODUKT menge="3">
				<POSITION>1</POSITION>
				<ART>Grippemittel Tumifla</ART>
				<EINZELPREIS>120.00</EINZELPREIS>
				<GESAMTPREIS>360.00</GESAMTPREIS>
				<MWST_PROZENT>19</MWST_PROZENT>
				<DATUM>8.8.201</DATUM>
			</PRODUKT>

			<PRODUKT menge="">
				<POSITION>2</POSITION>
				<ART>Beratung pauschal</ART>
				<EINZELPREIS></EINZELPREIS>
				<GESAMTPREIS>50.00</GESAMTPREIS>
				<MWST_PROZENT>19</MWST_PROZENT>
				<DATUM>8.8.201</DATUM>
			</PRODUKT>

			<PRODUKT menge="2">
				<POSITION>3</POSITION>
				<ART>Abführmittel "wech damit" pro Liter</ART>
				<EINZELPREIS>99.99</EINZELPREIS>
				<GESAMTPREIS>198.98</GESAMTPREIS>
				<MWST_PROZENT>19</MWST_PROZENT>
				<DATUM>8.8.201</DATUM>
			</PRODUKT>

			<PRODUKT menge="2">
				<POSITION>4</POSITION>
				<ART>Energieriegel "Satto"</ART>
				<EINZELPREIS>5.98</EINZELPREIS>
				<GESAMTPREIS>11.96</GESAMTPREIS>
				<MWST_PROZENT>7</MWST_PROZENT>
				<DATUM>8.8.201</DATUM>
			</PRODUKT>
		</PRODUKTE>
	</RECHNUNG>
</RECHNUNGEN>
