=== ermiS16/DeklrarativeProgrammierung/src/aufgabe3/rechnung.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns="hska.deklarativeProgrammierung"
	targetNamespace="hska.deklarativeProgrammierung"
	elementFormDefault="qualified">

	<xs:element name="RECHNUNGEN">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="RECHNUNG" minOccurs="1"
					maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="UNTERNEHMEN">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="NAME" type="xs:string" />
										<xs:element name="ADRESSE">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="STRASSE" type="xs:string" />
													<xs:element name="HAUSNUMMER" type="xs:string" />
													<xs:element name="PLZ">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="4" />
																<xs:pattern value="([A-Z][A-Z]-)?[0-9]{4,7}" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="ORT" type="xs:string" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="TELEFON" type="xs:string" minOccurs="0"/>
										<xs:element name="FAX" type="xs:string" minOccurs="0"/>
										<xs:element name="EMAIL" type="xs:string" minOccurs="0"/>
										<xs:element name="STEUERNUMMER" type="xs:string" />
										<xs:element name="ZAHLUNGSMOEGLICHKEITEN">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="BANKVERBINDUNG" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="BANK" type="xs:string" minOccurs="0"/>
																<xs:element name="IBAN" type="xs:string" minOccurs="0"/>
																<xs:element name="BIC" type="xs:string" minOccurs="0"/>
																<xs:element name="BLZ" type="xs:string" minOccurs="0"/>
																<xs:element name="KONTONUMMER" type="xs:string" minOccurs="0"/>
																<xs:element name="KONTOINHABER" type="xs:string" minOccurs="0"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="BITCOIN_ADRESSE" minOccurs="0">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="WALLET" type="xs:string" minOccurs="0"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>

							<xs:element name="ADRESSAT">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="ANREDE" type="xs:string" />
										<xs:element name="NAME" type="xs:string" />
										<xs:element name="ADRESSE">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="STRASSE" type="xs:string" />
													<xs:element name="HAUSNUMMER" type="xs:string" />
													<xs:element name="PLZ">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:minLength value="4" />
																<xs:pattern value="([A-Z][A-Z]-)?[0-9]{4,7}" />
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="ORT" type="xs:string" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>

							<xs:element name="RECHNUNGSDETAILS">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="RECHNUNGSDATUM" type="xs:date" />
										<xs:element name="RECHNUNGSNUMMER" type="xs:string" />
										<xs:element name="BETRAG">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="BRUTTO_GESAMT" type="xs:decimal"/>
													<xs:element name="NETTO_GESAMT" type="xs:decimal" minOccurs="0"/>
													<xs:element name="MWST_GESAMT" type="xs:decimal" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="WAEHRUNG" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>

							<xs:element name="PRODUKTE">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="PRODUKT" minOccurs="1"
											maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="POSITION" type="xs:unsignedInt"/>
													<xs:element name="ART" type="xs:string" />
													<xs:element name="EINZELPREIS" type="xs:string" minOccurs="0"/>
													<xs:element name="GESAMTPREIS" type="xs:string" />
													<xs:element name="MWST_PROZENT" type="xs:unsignedInt" minOccurs="0"/>
													<xs:element name="DATUM" type="xs:date"/>
												</xs:sequence>
												<xs:attribute name="menge" type="xs:string"
													use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ermiS16/DeklrarativeProgrammierung/src/aufgabe5/rechnung.xml
<?xml version="1.0" encoding="UTF-8" ?>

<RECHNUNGEN xmlns="hska.deklarativeProgrammierung"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="hska.deklarativeProgrammierung rechnung.xsd">

	<RECHNUNG>
		<UNTERNEHMEN>
			<NAME>Kleintier Meier GmbH</NAME>
			<ADRESSE>
				<STRASSE>Meierring</STRASSE>
				<HAUSNUMMER>3</HAUSNUMMER>
				<PLZ>82828</PLZ>
				<ORT>Machthausen</ORT>
			</ADRESSE>
			<TELEFON>0777/987987</TELEFON>
			<FAX>0777/987789</FAX>
			<EMAIL>klein.meier@tiere.de</EMAIL>
			<STEUERNUMMER>88 123/8282 2</STEUERNUMMER>
			<ZAHLUNGSMOEGLICHKEITEN>
				<BANKVERBINDUNG>
					<BANK>Sparkasse Karlsruhe</BANK>
					<BLZ>66050101</BLZ>
					<KONTONUMMER>987654321</KONTONUMMER>
					<KONTOINHABER>Kleintier Meier</KONTOINHABER>
				</BANKVERBINDUNG>
				<BITCOIN_ADRESSE></BITCOIN_ADRESSE>
			</ZAHLUNGSMOEGLICHKEITEN>
		</UNTERNEHMEN>

		<ADRESSAT>
			<ANREDE>Frau</ANREDE>
			<NAME>Sybille</NAME>
			<ADRESSE>
				<STRASSE>Am Süttelbach</STRASSE>
				<HAUSNUMMER>17</HAUSNUMMER>
				<PLZ>77070</PLZ>
				<ORT>Siedelsuderstadt</ORT>
			</ADRESSE>
		</ADRESSAT>

		<RECHNUNGSDETAILS>
			<RECHNUNGSDATUM>2017-01-15</RECHNUNGSDATUM>
			<RECHNUNGSNUMMER>657321</RECHNUNGSNUMMER>
			<BETRAG>
				<BRUTTO_GESAMT>962.22</BRUTTO_GESAMT>
				<NETTO_GESAMT>808.59</NETTO_GESAMT>
				<MWST_GESAMT>153.63</MWST_GESAMT>
			</BETRAG>
			<WAEHRUNG>€</WAEHRUNG>
		</RECHNUNGSDETAILS>

		<PRODUKTE>
			<PRODUKT menge="100">
				<POSITION>1</POSITION>
				<ART>Antike Holzwürmer</ART>
				<EINZELPREIS>1.50</EINZELPREIS>
				<GESAMTPREIS>150.00</GESAMTPREIS>
				<MWST_PROZENT>19</MWST_PROZENT>
				<DATUM>2017-01-01</DATUM>
			</PRODUKT>

			<PRODUKT menge="1">
				<POSITION>2</POSITION>
				<ART>Holzwurmfutter</ART>
				<EINZELPREIS>34.45</EINZELPREIS>
				<GESAMTPREIS>34.45</GESAMTPREIS>
				<MWST_PROZENT>19</MWST_PROZENT>
				<DATUM>2017-01-12</DATUM>
			</PRODUKT>

			<PRODUKT menge="1">
				<POSITION>3</POSITION>
				<ART>Steinlaus, Petrophaga lorioti</ART>
				<EINZELPREIS>777.77</EINZELPREIS>
				<GESAMTPREIS>777.77</GESAMTPREIS>
				<MWST_PROZENT>19</MWST_PROZENT>
				<DATUM>2017-01-12</DATUM>
			</PRODUKT>
		</PRODUKTE>
	</RECHNUNG>

	<RECHNUNG>
		<UNTERNEHMEN>
			<NAME>Rochade-La Hoff Pharma GmbH</NAME>
			<ADRESSE>
				<STRASSE>An der Chemie</STRASSE>
				<HAUSNUMMER>17</HAUSNUMMER>
				<PLZ>79639</PLZ>
				<ORT>Grenzych-Wahlen</ORT>
			</ADRESSE>
			<TELEFON>07624/666333999</TELEFON>
			<FAX>07624/666333990</FAX>
			<EMAIL></EMAIL>
			<STEUERNUMMER>DE333666999</STEUERNUMMER>
			<ZAHLUNGSMOEGLICHKEITEN>
				<BANKVERBINDUNG>
					<BANK>Deutsche Bank Lörrach</BANK>
					<IBAN>DE18 6837 0034 0999 6663 33</IBAN>
					<BIC>DEUTDE6F683</BIC>
				</BANKVERBINDUNG>
				<BITCOIN_ADRESSE></BITCOIN_ADRESSE>
			</ZAHLUNGSMOEGLICHKEITEN>
		</UNTERNEHMEN>

		<ADRESSAT>
			<ANREDE>Dr. med</ANREDE>
			<NAME>Cyprian Zottel</NAME>
			<ADRESSE>
				<STRASSE>Soddelstudel</STRASSE>
				<HAUSNUMMER>5a</HAUSNUMMER>
				<PLZ>13023</PLZ>
				<ORT>Zotenheim</ORT>
			</ADRESSE>
		</ADRESSAT>

		<RECHNUNGSDETAILS>
			<RECHNUNGSDATUM>2017-08-08</RECHNUNGSDATUM>
			<RECHNUNGSNUMMER>98-798-7987</RECHNUNGSNUMMER>
			<BETRAG>
				<BRUTTO_GESAMT>621.24</BRUTTO_GESAMT>
				<NETTO_GESAMT>490.22</NETTO_GESAMT>
				<MWST_GESAMT>116.74</MWST_GESAMT>
			</BETRAG>
			<WAEHRUNG>€</WAEHRUNG>
		</RECHNUNGSDETAILS>

		<PRODUKTE>
			<PRODUKT menge="3">
				<POSITION>1</POSITION>
				<ART>Grippemittel Tumifla</ART>
				<EINZELPREIS>120.00</EINZELPREIS>
				<GESAMTPREIS>360.00</GESAMTPREIS>
				<MWST_PROZENT>19</MWST_PROZENT>
				<DATUM>2017-08-08</DATUM>
			</PRODUKT>

			<PRODUKT menge="">
				<POSITION>2</POSITION>
				<ART>Beratung pauschal</ART>
				<EINZELPREIS></EINZELPREIS>
				<GESAMTPREIS>50.00</GESAMTPREIS>
				<MWST_PROZENT>19</MWST_PROZENT>
				<DATUM>2017-08-08</DATUM>
			</PRODUKT>

			<PRODUKT menge="2">
				<POSITION>3</POSITION>
				<ART>Abführmittel "wech damit" pro Liter</ART>
				<EINZELPREIS>99.99</EINZELPREIS>
				<GESAMTPREIS>198.98</GESAMTPREIS>
				<MWST_PROZENT>19</MWST_PROZENT>
				<DATUM>2017-08-08</DATUM>
			</PRODUKT>

			<PRODUKT menge="2">
				<POSITION>4</POSITION>
				<ART>Energieriegel "Satto"</ART>
				<EINZELPREIS>5.98</EINZELPREIS>
				<GESAMTPREIS>11.96</GESAMTPREIS>
				<MWST_PROZENT>7</MWST_PROZENT>
				<DATUM>2017-08-08</DATUM>
			</PRODUKT>
		</PRODUKTE>
	</RECHNUNG>

	<RECHNUNG>
		<UNTERNEHMEN>
			<NAME>Bestattungen Unterberg</NAME>
			<ADRESSE>
				<STRASSE>Oberbergweg</STRASSE>
				<HAUSNUMMER>5</HAUSNUMMER>
				<PLZ>43210</PLZ>
				<ORT>Ultursingen</ORT>
			</ADRESSE>
			<TELEFON>0478/777 555</TELEFON>
			<FAX></FAX>
			<EMAIL>unter@berg.de</EMAIL>
			<STEUERNUMMER>DE987654321</STEUERNUMMER>
			<ZAHLUNGSMOEGLICHKEITEN>
				<BANKVERBINDUNG>
					<BANK>UBS Zürich</BANK>
					<IBAN>DE16 6605 0101 0077 8899 11</IBAN>
					<BIC>UBSWCHZH80H</BIC>
					<KONTONUMMER>75847683</KONTONUMMER>
				</BANKVERBINDUNG>
				<BITCOIN_ADRESSE>
					<WALLET>1P82rBiJHDFSav2QrKx1bvdDRVh5QnGkkZ</WALLET>
				</BITCOIN_ADRESSE>
			</ZAHLUNGSMOEGLICHKEITEN>
		</UNTERNEHMEN>

		<ADRESSAT>
			<ANREDE>Familie</ANREDE>
			<NAME>Ursel</NAME>
			<ADRESSE>
				<STRASSE>Ulturenstraße</STRASSE>
				<HAUSNUMMER>764</HAUSNUMMER>
				<PLZ>43210</PLZ>
				<ORT>Ultursingen</ORT>
			</ADRESSE>
		</ADRESSAT>

		<RECHNUNGSDETAILS>
			<RECHNUNGSDATUM>2017-10-19</RECHNUNGSDATUM>
			<RECHNUNGSNUMMER>893 213 11</RECHNUNGSNUMMER>
			<BETRAG>
				<BRUTTO_GESAMT>878.49</BRUTTO_GESAMT>
				<NETTO_GESAMT>738.23</NETTO_GESAMT>
				<MWST_GESAMT>140.24</MWST_GESAMT>
			</BETRAG>
			<WAEHRUNG>€</WAEHRUNG>
		</RECHNUNGSDETAILS>

		<PRODUKTE>
			<PRODUKT menge="1">
				<POSITION>1</POSITION>
				<ART>Urne, Eiche massiv</ART>
				<EINZELPREIS></EINZELPREIS>
				<GESAMTPREIS>299.99</GESAMTPREIS>
				<MWST_PROZENT>19</MWST_PROZENT>
				<DATUM>2017-10-19</DATUM>
			</PRODUKT>

			<PRODUKT menge="1">
				<POSITION>2</POSITION>
				<ART>Überführung Krematorium Feuerbach inkl. Begleitpersonal</ART>
				<EINZELPREIS></EINZELPREIS>
				<GESAMTPREIS>349.00</GESAMTPREIS>
				<MWST_PROZENT>19</MWST_PROZENT>
				<DATUM>2017-10-19</DATUM>
			</PRODUKT>

			<PRODUKT menge="1">
				<POSITION>3</POSITION>
				<ART>Dekoration</ART>
				<EINZELPREIS></EINZELPREIS>
				<GESAMTPREIS>149.50</GESAMTPREIS>
				<MWST_PROZENT>19</MWST_PROZENT>
				<DATUM>2017-10-19</DATUM>
			</PRODUKT>

			<PRODUKT menge="40">
				<POSITION>4</POSITION>
				<ART>Trauerkarten inkl. Briefmarken</ART>
				<EINZELPREIS>2.00</EINZELPREIS>
				<GESAMTPREIS>80.00</GESAMTPREIS>
				<MWST_PROZENT>19</MWST_PROZENT>
				<DATUM>2017-10-19</DATUM>
			</PRODUKT>
		</PRODUKTE>
	</RECHNUNG>

	<RECHNUNG>
		<UNTERNEHMEN>
			<NAME>Weinhandel von Langres</NAME>
			<ADRESSE>
				<STRASSE>Emilianigasse</STRASSE>
				<HAUSNUMMER>19</HAUSNUMMER>
				<PLZ>86866</PLZ>
				<ORT>Mickhause</ORT>
			</ADRESSE>
			<STEUERNUMMER>DE123456789</STEUERNUMMER>
			<ZAHLUNGSMOEGLICHKEITEN>
				<BANKVERBINDUNG>
					<BANK>Pax-Bank Köln</BANK>
					<BLZ>370 601 93</BLZ>
					<KONTONUMMER>80200601</KONTONUMMER>
				</BANKVERBINDUNG>
			</ZAHLUNGSMOEGLICHKEITEN>
		</UNTERNEHMEN>

		<ADRESSAT>
			<ANREDE>Seine Exzellenz der Hochwürdigste Herr</ANREDE>
			<NAME>Waldus Mikksa</NAME>
			<ADRESSE>
				<STRASSE>Fronhof</STRASSE>
				<HAUSNUMMER>4</HAUSNUMMER>
				<PLZ>86152</PLZ>
				<ORT>Augsburg</ORT>
			</ADRESSE>
		</ADRESSAT>

		<RECHNUNGSDETAILS>
			<RECHNUNGSDATUM>2009-11-07</RECHNUNGSDATUM>
			<RECHNUNGSNUMMER>611-555-32</RECHNUNGSNUMMER>
			<BETRAG>
				<BRUTTO_GESAMT>2359.88</BRUTTO_GESAMT>
				<MWST_GESAMT>376.79</MWST_GESAMT>
			</BETRAG>
			<WAEHRUNG>€</WAEHRUNG>
		</RECHNUNGSDETAILS>

		<PRODUKTE>
			<PRODUKT menge="1">
				<POSITION>1</POSITION>
				<ART>"Liebliche Gottesmilbe"</ART>
				<EINZELPREIS></EINZELPREIS>
				<GESAMTPREIS>2299.98</GESAMTPREIS>
				<MWST_PROZENT>19</MWST_PROZENT>
				<DATUM>2009-11-07</DATUM>
			</PRODUKT>

			<PRODUKT menge="100">
				<POSITION>2</POSITION>
				<ART>Standardweingläser "Schluck"</ART>
				<GESAMTPREIS>59.90</GESAMTPREIS>
				<MWST_PROZENT>19</MWST_PROZENT>
				<DATUM>2009-11-07</DATUM>
			</PRODUKT>
		</PRODUKTE>
	</RECHNUNG>

	<RECHNUNG>
		<UNTERNEHMEN>
			<NAME>Peer Weidman</NAME>
			<ADRESSE>
				<STRASSE>Kürschnergasse</STRASSE>
				<HAUSNUMMER>77</HAUSNUMMER>
				<PLZ>76131</PLZ>
				<ORT>Karlsgrube</ORT>
			</ADRESSE>
		</UNTERNEHMEN>

		<ADRESSAT>
			<ANREDE>Herr</ANREDE>
			<NAME>Claudius Artemis</NAME>
			<ADRESSE>
				<STRASSE>Am Wolfsweiher</STRASSE>
				<HAUSNUMMER>7</HAUSNUMMER>
				<PLZ>56741</PLZ>
				<ORT>Hirschhausen</ORT>
			</ADRESSE>
		</ADRESSAT>

		<RECHNUNGSDETAILS>
			<RECHNUNGSDATUM>2017-08.09</RECHNUNGSDATUM>
			<RECHNUNGSNUMMER>1</RECHNUNGSNUMMER>
			<BETRAG>
				<BRUTTO_GESAMT>3598.99</BRUTTO_GESAMT>
			</BETRAG>
			<WAEHRUNG>€</WAEHRUNG>
		</RECHNUNGSDETAILS>

		<PRODUKTE>
			<PRODUKT menge="1">
				<POSITION>1</POSITION>
				<ART>Vogelschnepper, um 1600</ART>
				<GESAMTPREIS>3499.00</GESAMTPREIS>
				<DATUM>2017-08.09</DATUM>
			</PRODUKT>

			<PRODUKT menge="200">
				<POSITION>2</POSITION>
				<ART>Schusse, um 1720</ART>
				<GESAMTPREIS>9.99</GESAMTPREIS>
				<DATUM>2017-08.09</DATUM>
			</PRODUKT>
		</PRODUKTE>
	</RECHNUNG>
</RECHNUNGEN>
